name: Twemoji Version Check.

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Twemoji Version Check
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current Twemoji version
        id: current-twemoji-version
        run: |
          CURRENT_VERSION=$(jq -r '.packages["node_modules/@twemoji/api"].version' "package-lock.json");
          echo "Current Twemoji Version: $CURRENT_VERSION";
          echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT;

      - name: Get the latest Twemoji version
        id: latest-twemoji-version
        run: |
          LATEST_VERSION=$(curl -s https://registry.npmjs.org/@twemoji/api/latest | jq -r '.version');
          echo "Latest Twemoji Version: $LATEST_VERSION";
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT;

      - name: Check for existing issue
        id: check-issue
        env:
          LATEST_VERSION: ${{ steps.latest-twemoji-version.outputs.latest_version }}
        run: |
          echo "Checking for existing issue";
          ISSUE_NUMBER=$(gh issue list --search "Update Twemoji to ${LATEST_VERSION}" --json number --jq '.[0].number');
          # Set the output to the issue number
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV;

      - name: Compare versions.
        id: compare-versions
        run: |
          if [ "${{ steps.current-twemoji-version.outputs.current_version }}" != "${{ steps.latest-twemoji-version.outputs.latest_version }}" ]; then
            echo "::set-output name=update_required::true";
          elif [ "${{ steps.check-issue.outputs.issue_number }}" != '' ]; then
            echo "::set-output name=update_required::false";
          else
            echo "::set-output name=update_required::false";
          fi

      - name: Set up PHP.
        if: steps.compare-versions.outputs.update_required == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Create issue
        id: create-issue
        if: steps.compare-versions.outputs.update_required == 'true'
        run: |
          echo "Creating issue";
          # Read in content from `.github/version-bump-issue.md`
          ISSUE_BODY=$(cat .github/version-bump-issue.md);
          # Replace the placeholders with the actual values
          # First replace '%%CURRENT_VERSION%%' with the current version
          ISSUE_BODY=$(echo "$ISSUE_BODY" | sed "s/%%CURRENT_VERSION%%/${{ steps.current-twemoji-version.outputs.current_version }}/g");
          # Then replace '%%LATEST_VERSION%%' with the latest version
          ISSUE_BODY=$(echo "$ISSUE_BODY" | sed "s/%%LATEST_VERSION%%/${{ steps.latest-twemoji-version.outputs.latest_version }}/g");
          # Create the issue
          gh issue create --title "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --body "$ISSUE_BODY" --assignee peterwilsoncc;
          # Get the issue number
          ISSUE_NUMBER=$(gh issue list --search "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --json number --jq '.[0].number');
          # Set the output to the issue number
          echo "::set-output name=issue_number::$ISSUE_NUMBER";

      - name: Run the update script.
        id: run-update
        if: steps.compare-versions.outputs.update_required == 'true'
        run: |
          echo "Running the update script";
          ./bin/tw-version-update.sh;
          git config --global user.email "bot@peterwilson.cc";
          git config --global user.name "Bot";
          git checkout -b "update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }}";
          git add .;
          git commit -am "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}";
          git push origin "update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }}";

      - name: Check if PR is required
        id: check-pr
        if: steps.compare-versions.outputs.update_required == 'true'
        run: |
          echo "Checking if PR is required";
          # Search for existing PR via branch name
          PR_NUMBER=$(gh pr list --head update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }} --json number --json number --jq '.[0].number');
          # If the PR exists, no new PR is required, set output to false
          if [ -n "$PR_NUMBER" ]; then
            echo "::set-output name=pr_required::false";
          else
            echo "::set-output name=pr_required::true";
          fi

      - name: Create pull request.
        id: create-pr
        if: steps.compare-versions.outputs.update_required == 'true' && steps.check-pr.outputs.pr_required == 'true'
        run: |
          echo "Creating pull request";
          # Read in content from `.github/version-bump-pr.md`
          PR_BODY=$(cat .github/version-bump-pr.md);
          # Replace the placeholders with the actual values
          # Then replace '%%LATEST_VERSION%%' with the latest version
          PR_BODY=$(echo "$PR_BODY" | sed "s/%%LATEST_VERSION%%/${{ steps.latest-twemoji-version.outputs.latest_version }}/g");
          # Replace '%%ISSUE_NUMBER%%' with the issue number
          PR_BODY=$(echo "$PR_BODY" | sed "s/%%ISSUE_NUMBER%%/${{ steps.check-issue.outputs.issue_number }}/g");
          # Create the pull request
          gh pr create --title "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --body "$PR_BODY" --base main --head update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }} --assignee peterwilsoncc;
          # Get the pull request number
          PR_NUMBER=$(gh pr list --search "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --json number --jq '.[0].number');
          # Set the output to the pull request number
          echo "::set-output name=pr_number::$PR_NUMBER";
