name: Twemoji Version Check.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

jobs:
  run:
    name: Twemoji Version Check
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current Twemoji version
        id: current-twemoji-version
        run: |
          CURRENT_VERSION=$(jq -r '.packages["node_modules/@twemoji/api"].version' "package-lock.json");
          echo "Current Twemoji Version: $CURRENT_VERSION";
          echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT;

      - name: Get the latest Twemoji version
        id: latest-twemoji-version
        run: |
          LATEST_VERSION=$(curl -s https://registry.npmjs.org/@twemoji/api/latest | jq -r '.version');
          echo "Latest Twemoji Version: $LATEST_VERSION";
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_OUTPUT;

      - name: Check for existing issue
        id: check-issue
        env:
          LATEST_VERSION: ${{ steps.latest-twemoji-version.outputs.latest_version }}
        run: |
          echo "Checking for existing issue";
          ISSUE_NUMBER=$(gh issue list --search "Update Twemoji to ${LATEST_VERSION}" --json number --jq '.[0].number');
          echo "Issue number: $ISSUE_NUMBER";
          # Set the output to the issue number
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_OUTPUT;

      - name: Compare versions.
        id: compare-versions
        run: |
          if [ "${{ steps.check-issue.outputs.issue_number }}" != '' ]; then
            echo "issue_required=false" >> $GITHUB_OUTPUT;
            echo "update_required=true" >> $GITHUB_OUTPUT;
          elif [ "${{ steps.current-twemoji-version.outputs.current_version }}" != "${{ steps.latest-twemoji-version.outputs.latest_version }}" ]; then
            echo "issue_required=true" >> $GITHUB_OUTPUT
            echo "update_required=true" >> $GITHUB_OUTPUT;
          else
            echo "issue_required=false" >> $GITHUB_OUTPUT;
            echo "update_required=false" >> $GITHUB_OUTPUT;
          fi

      - name: Create or get issue
        id: create-issue
        run: |
          if [ "${{ steps.compare-versions.outputs.issue_required }}" == 'false' ]; then
            ISSUE_NUMBER="${{ steps.check-issue.outputs.issue_number }}";
            echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_OUTPUT;
            echo "No issue required, skipping issue creation.";
            exit 0;
          fi
          echo "Creating issue";
          # Read in content from `.github/version-bump-issue.md`
          ISSUE_BODY=$(cat .github/version-bump-issue.md);
          # Replace the placeholders with the actual values
          # First replace '%%CURRENT_VERSION%%' with the current version
          ISSUE_BODY=$(echo "$ISSUE_BODY" | sed "s/%%CURRENT_VERSION%%/${{ steps.current-twemoji-version.outputs.current_version }}/g");
          # Then replace '%%LATEST_VERSION%%' with the latest version
          ISSUE_BODY=$(echo "$ISSUE_BODY" | sed "s/%%LATEST_VERSION%%/${{ steps.latest-twemoji-version.outputs.latest_version }}/g");
          # Create the issue
          ISSUE_LINK=$(gh issue create --title "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --body "$ISSUE_BODY" --assignee peterwilsoncc;)
          # Echo the issue link.
          echo "Issue link: $ISSUE_LINK";

          # Set the output to the issue number
          # Issue number is the last part of the URL following the final `/`.
          ISSUE_NUMBER=$(echo $ISSUE_LINK | awk -F/ '{print $NF}');
          echo "issue_number=${ISSUE_NUMBER}" >> $GITHUB_OUTPUT;
          # Set the output to the issue number
          echo "issue_link=${ISSUE_LINK}" >> $GITHUB_OUTPUT;

      - name: Check if PR is required
        id: check-pr
        if: ${{ steps.compare-versions.outputs.update_required == 'true' }}
        run: |
          echo "Checking if PR is required";
          # Search for existing PR via branch name
          PR_NUMBER=$(gh pr list --head update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }} --json number --json number --jq '.[0].number');
          # If the PR exists, no new PR is required, set output to false
          if [ -n "$PR_NUMBER" ]; then
            echo "pr_required=false" >> $GITHUB_OUTPUT;
          else
            echo "pr_required=true" >> $GITHUB_OUTPUT;
          fi

      - name: Run the update script.
        id: run-update
        if: ${{ steps.compare-versions.outputs.update_required == 'true' && steps.check-pr.outputs.pr_required == 'true' }}
        run: |
          echo "Running the update script";
          ./bin/tw-version-update.sh;
          git config --global user.email "bot@peterwilson.cc";
          git config --global user.name "Bot";
          git checkout -b "update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }}";
          git add .;
          git commit -am "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}";
          git push origin "update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }}";

      - name: Create pull request.
        id: create-pr
        if: ${{ steps.compare-versions.outputs.update_required == 'true' && steps.check-pr.outputs.pr_required == 'true' }}
        run: |
          echo "Creating pull request";
          # Read in content from `.github/version-bump-pr.md`
          PR_BODY=$(cat .github/version-bump-pr.md);
          # Replace the placeholders with the actual values
          # Then replace '%%LATEST_VERSION%%' with the latest version
          PR_BODY=$(echo "$PR_BODY" | sed "s/%%LATEST_VERSION%%/${{ steps.latest-twemoji-version.outputs.latest_version }}/g");
          # Replace '%%ISSUE_NUMBER%%' with the issue number
          PR_BODY=$(echo "$PR_BODY" | sed "s/%%ISSUE_NUMBER%%/${{ steps.create-issue.outputs.issue_number }}/g");
          # Create the pull request
          gh pr create --title "Update Twemoji to ${{ steps.latest-twemoji-version.outputs.latest_version }}" --body "$PR_BODY" --base main --head update-twemoji-${{ steps.latest-twemoji-version.outputs.latest_version }} --assignee peterwilsoncc --reviewer peterwilsoncc;
